version: '3'

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }
  production_traefik: { }
  production_django_media: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: project_production_django
    volumes:
      - /var/www/api.nursaloh.uz/media:/app/project/media
      - /var/www/api.nursaloh.uz/static:/app/project/static
    depends_on:
      - postgres
      - redis
    ports:
      - 5000:5000
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: project_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: project_production_celeryworker
    container_name: project_production_celeryworker
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: project_production_celerybeat
    container_name: project_production_celerybeat
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celerybeat
