# Generated by Django 4.1.4 on 2024-01-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                error_messages={"unique": "A user with that phone already exists."},
                help_text="Required. 13 characters or fewer.",
                max_length=20,
                unique=True,
                verbose_name="Phone",
            ),
        ),
    ]
